# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20170328_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_key2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_time2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube 링크'),
        ),
    ]
