# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20170402_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=study.models.user_path),
        ),
    ]
