# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to=study.models.user_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=2, upload_to=study.models.user_path),
            preserve_default=False,
        ),
    ]
