# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0001_initial'),
        ('study', '0008_auto_20170416_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='cover_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_key',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_key2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_time2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_url2',
        ),
        migrations.AddField(
            model_name='post',
            name='attachment_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_summernote.Attachment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
