# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_auto_20170516_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_date',
        ),
    ]
