# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_auto_20170516_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
